/**
 * API template
 * API template description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatDto } from './chatDto';


export interface MessageDto { 
    id?: string;
    creationDate?: Date;
    modifDate?: Date;
    archived: boolean;
    content: string;
    userId: string;
    chat?: ChatDto;
    chatId: string;
}

